openapi: 3.0.0
info:
  title: Sample API definitions
  version: 1.0.0

paths: {}
components:
  schemas:
    ExternalRef:
      type: string
    ExternalObject:
      type: object
      properties:
        field1:
          type: string
        field2:
          $ref: '#/components/schemas/ExternalRef2'
    ExternalRef2:
      type: object
      properties:
        subfield1:
          type: string