package generator

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-faster/errors"

	"github.com/sintoniastrategy/validgo-gen/internal/generator/astbuilder"
)

type HandlersFile struct {
	requiredFieldsArePointers bool
	packageName               string
	interfaceDecls            []*ast.GenDecl

	handlerDeclBuilder *astbuilder.StructBuilder

	handlerConstructorDecl                       *ast.FuncDecl
	handlerConstructorDeclQAArgs                 *ast.FieldList    // quick access to handler constructor args
	handlerConstructorDeclQAConstructorComposite *ast.CompositeLit // quick access to handler struct initializer

	addRoutesDecl         *ast.FuncDecl
	handleDeclQASwitches  map[string]*ast.BlockStmt
	restDecls             []*ast.FuncDecl
	hasContainsNullMethod bool
}

func (g *Generator) InitHandlerImports() {
	g.AddHandlersImport("github.com/go-playground/validator/v10")
	g.AddHandlersImport("github.com/go-chi/chi/v5")
}

func (g *Generator) InitHandlerStruct() {
	g.HandlersFile.handlerDeclBuilder = astbuilder.NewStructBuilder().WithName("Handler").
		AddField(astbuilder.NewFieldBuilder().WithName("validator").WithType(
			astbuilder.NewSimpleTypeBuilder().AddElements("validator", "Validate").AsPointer(true)))
}

func (g *Generator) InitHandlerConstructor() {
	initializerComposite := astbuilder.CompositeLit(astbuilder.Ident("Handler"),
		astbuilder.KeyValue(astbuilder.I("validator"), astbuilder.Call(astbuilder.Sel(astbuilder.I("validator"), "New"),
			astbuilder.Call(astbuilder.Sel(astbuilder.I("validator"), "WithRequiredStructEnabled")),
		)),
	)

	g.HandlersFile.handlerConstructorDecl = astbuilder.NewFunctionBuilder().
		WithName("NewHandler").
		AddResult(astbuilder.NewFieldBuilder().WithType(astbuilder.Ident("Handler").AsPointer(true))).
		Build()
	g.HandlersFile.handlerConstructorDecl.Body.List = []ast.Stmt{astbuilder.Return1(astbuilder.Amp(initializerComposite)).Build()}

	g.HandlersFile.handlerConstructorDeclQAArgs = g.HandlersFile.handlerConstructorDecl.Type.Params
	g.HandlersFile.handlerConstructorDeclQAConstructorComposite = initializerComposite
}

func (g *Generator) InitRoutesFunc() {
	g.HandlersFile.addRoutesDecl = astbuilder.NewFunctionBuilder().
		WithName("AddRoutes").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("router").WithType(astbuilder.Selector("chi", "Router"))).
		Build()
}

func (g *Generator) InitHandlerFields(packageName string) {
	g.HandlersFile.packageName = packageName

	g.InitHandlerImports()

	g.InitHandlerStruct()

	g.InitHandlerConstructor()

	g.InitRoutesFunc()
}

func (g *Generator) NewHandlersFile() {
	g.HandlersFile = &HandlersFile{
		requiredFieldsArePointers: g.Opts.RequiredFieldsArePointers,
	}
}

func (g *Generator) WriteHandlersToOutput(output io.Writer) error {
	const op = "generator.HandlersFile.WriteToOutput"
	// go/ast package is great!
	_, err := output.Write([]byte("// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.\n\n"))
	if err != nil {
		return errors.Wrap(err, op)
	}

	file := g.GenerateHandlersFile()
	err = format.Node(output, token.NewFileSet(), file)
	if err != nil {
		return errors.Wrap(err, op)
	}

	return nil
}

func (g *Generator) AddHandlersInterface(name string, methodName string, requestName string, responseName string) {
	interfaceBuilder := astbuilder.NewInterfaceBuilder().WithName(name).WithMethod(
		astbuilder.NewInterfaceMethodBuilder().WithName(methodName).
			AddArgField(
				astbuilder.NewFieldBuilder().WithName("ctx").WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements("context", "Context"),
				)).
			AddArgField(
				astbuilder.NewFieldBuilder().WithName("r").WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements(
						g.GetCurrentModelsPackage(), requestName,
					))).
			AddRetvalField(
				astbuilder.NewFieldBuilder().WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements(
						g.GetCurrentModelsPackage(), responseName,
					).AsPointer(true))).
			AddRetvalField(
				astbuilder.NewFieldBuilder().WithType(
					astbuilder.NewSimpleTypeBuilder().AddElement("error")),
			),
	)

	g.HandlersFile.interfaceDecls = append(g.HandlersFile.interfaceDecls, interfaceBuilder.Build())
}

func (g *Generator) AddDependencyToHandlers(baseName string) {
	fieldName := GoIdentLowercase(baseName)

	g.HandlersFile.handlerDeclBuilder.AddField(
		astbuilder.NewFieldBuilder().WithName(fieldName).WithType(
			astbuilder.NewSimpleTypeBuilder().AddElement(baseName + "Handler")))

	g.HandlersFile.handlerConstructorDeclQAArgs.List = append(g.HandlersFile.handlerConstructorDeclQAArgs.List,
		astbuilder.IdentField(fieldName, baseName+"Handler").Build())

	g.HandlersFile.handlerConstructorDeclQAConstructorComposite.Elts = append(
		g.HandlersFile.handlerConstructorDeclQAConstructorComposite.Elts,
		astbuilder.KeyValue(astbuilder.I(fieldName), astbuilder.I(fieldName)),
	)
}

func (g *Generator) AddHandlersImport(path string) {
	g.HandlerImportsBuilder.AddImport(path)
}

func (g *Generator) GenerateHandlersFile() *ast.File {
	importSpecs, declSpecs := g.HandlerImportsBuilder.Build()

	g.FinalizeHandlerSwitches()

	fb := astbuilder.NewFileBuilder(g.HandlersFile.packageName).
		WithImports(importSpecs, declSpecs)
	for _, d := range g.HandlersFile.interfaceDecls {
		fb.AddDecl(d)
	}
	fb.AddDecl(g.HandlersFile.handlerDeclBuilder.BuildAsDeclaration())
	fb.AddDecl(g.HandlersFile.handlerConstructorDecl)
	fb.AddDecl(g.HandlersFile.addRoutesDecl)
	for _, d := range g.HandlersFile.restDecls {
		fb.AddDecl(d)
	}

	return fb.Build()
}

func (g *Generator) AddRouteToRouter(baseName string, method string, pathName string) {
	g.HandlersFile.addRoutesDecl.Body.List = append(g.HandlersFile.addRoutesDecl.Body.List,
		astbuilder.CallStmt(
			astbuilder.Sel(astbuilder.I("router"), method),
			astbuilder.Str(pathName),
			astbuilder.Sel(astbuilder.I("h"), "handle"+baseName),
		).Build())
}

func (g *Generator) GetHandler(baseName string) *ast.BlockStmt {
	if g.HandlersFile.handleDeclQASwitches == nil {
		return nil
	}
	if blockStmt, ok := g.HandlersFile.handleDeclQASwitches[baseName]; ok {
		return blockStmt
	}

	return nil
}

func (g *Generator) CreateHandler(baseName string) {
	g.AddHandlersImport("mime")

	switchBody := astbuilder.NewBodyBuilder().Build()

	handleFunc := astbuilder.NewFunctionBuilder().
		WithName("handle"+baseName).
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true))).
		Build()

	handleFunc.Body.List = []ast.Stmt{
		astbuilder.NewDefineBuilder().
						Lhs(astbuilder.I("contentType"), astbuilder.I("_"), astbuilder.I("_")).
						AddRhs(astbuilder.Call(astbuilder.Sel(astbuilder.I("mime"), "ParseMediaType"),
				astbuilder.Call(astbuilder.Sel(astbuilder.I("r.Header"), "Get"), astbuilder.Str("Content-Type")),
			)).Build(),
		astbuilder.Switch(astbuilder.I("contentType")).Build(),
	}
	// Replace the switch body with our tracked one
	handleFunc.Body.List[1].(*ast.SwitchStmt).Body = switchBody

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, handleFunc)

	if g.HandlersFile.handleDeclQASwitches == nil {
		g.HandlersFile.handleDeclQASwitches = make(map[string]*ast.BlockStmt)
	}
	g.HandlersFile.handleDeclQASwitches[baseName] = switchBody
}

// CreateDirectHandler generates a handler that directly delegates to the request handler
// without checking Content-Type. Used for operations with no request body (e.g. GET, DELETE)
// where Content-Type is irrelevant.
func (g *Generator) CreateDirectHandler(baseName string) {
	handleFunc := astbuilder.NewFunctionBuilder().
		WithName("handle" + baseName).
		WithReceiver(astbuilder.NewFieldBuilder().
			WithName("h").
			WithType(astbuilder.Ident("Handler").AsPointer(true))).
		AddParams(
			astbuilder.SelectorField("w", "http", "ResponseWriter"),
			astbuilder.NewFieldBuilder().
				WithName("r").
				WithType(astbuilder.Selector("http", "Request").AsPointer(true)),
		).
		WithBody(astbuilder.NewBodyBuilder().
			Call(astbuilder.Sel(astbuilder.I("h"), "handle"+baseName+"Request"), astbuilder.I("w"), astbuilder.I("r")),
		).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, handleFunc)
}

func (g *Generator) FinalizeHandlerSwitches() {
	if g.HandlersFile.handleDeclQASwitches == nil {
		return
	}
	for _, blockStmt := range g.HandlersFile.handleDeclQASwitches {
		blockStmt.List = append(blockStmt.List,
			astbuilder.Default().WithBody(astbuilder.NewBodyBuilder().
				AddStmt(astbuilder.CallStmt(
					astbuilder.Sel(astbuilder.I("http"), "Error"),
					astbuilder.I("w"),
					astbuilder.Str("{\"error\":\"Unsupported Content-Type\"}"),
					astbuilder.Sel(astbuilder.I("http"), "StatusUnsupportedMediaType"),
				)).
				AddStmt(astbuilder.Return()),
			).Build())
	}
}

func (g *Generator) AddContentTypeHandler(baseName string, rawContentType string) {
	if g.HandlersFile.handleDeclQASwitches == nil {
		return
	}
	if blockStmt, ok := g.HandlersFile.handleDeclQASwitches[baseName]; ok {
		caseBody := astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"), "handle"+baseName+"Request"), astbuilder.I("w"), astbuilder.I("r"))).
			AddStmt(astbuilder.Return())

		blockStmt.List = append(blockStmt.List,
			astbuilder.Case(astbuilder.Str(rawContentType)).WithBody(caseBody).Build())

		if rawContentType == applicationJSONCT {
			blockStmt.List = append(blockStmt.List,
				astbuilder.Case(astbuilder.Str("")).WithBody(caseBody).Build())
		}
	}
}

func (g *Generator) AddHandleOperationMethodHandlers(baseName string) {
	body := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DefineCallWithErr("request",
			astbuilder.Sel(astbuilder.I("h"), "parse"+baseName+"Request"), astbuilder.I("r"))).
		AddStmt(astbuilder.IfErrNotNil().WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.I("http"), "Error"),
				astbuilder.I("w"),
				astbuilder.Call(astbuilder.Sel(astbuilder.I("fmt"), "Sprintf"),
					astbuilder.Str("{\"error\":%s}"),
					astbuilder.Call(astbuilder.Sel(astbuilder.I("strconv"), "Quote"),
						astbuilder.Call(astbuilder.Sel(astbuilder.I("err"), "Error")),
					),
				),
				astbuilder.Sel(astbuilder.I("http"), "StatusBadRequest"),
			)).
			AddStmt(astbuilder.Return()))).
		AddStmt(astbuilder.DefineCall("ctx", astbuilder.Sel(astbuilder.I("r"), "Context"))).
		AddStmt(astbuilder.DefineCallWithErr("response",
			astbuilder.Sel(astbuilder.Sel(astbuilder.I("h"), GoIdentLowercase(baseName)), "Handle"+baseName),
			astbuilder.I("ctx"), astbuilder.Star(astbuilder.I("request")))).
		AddStmt(astbuilder.If(astbuilder.Or(astbuilder.Ne(astbuilder.I("err"), astbuilder.I("nil")), astbuilder.Eq(astbuilder.I("response"), astbuilder.I("nil")))).
			WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.I("http"), "Error"),
				astbuilder.I("w"),
				astbuilder.Str("{\"error\":\"InternalServerError\"}"),
				astbuilder.Sel(astbuilder.I("http"), "StatusInternalServerError"),
			)).
			AddStmt(astbuilder.Return()))).
		AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"), "write"+baseName+"Response"), astbuilder.I("w"), astbuilder.I("response"))).
		AddStmt(astbuilder.Return())

	fn := astbuilder.NewFunctionBuilder().
		WithName("handle"+baseName+"Request").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true))).
		WithBody(body).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, fn)
	g.AddHandlersImport("fmt")
	g.AddHandlersImport("strconv")
}

func (g *Generator) AddWriteResponseMethodHandlers(baseName string, codes []string, operation *openapi3.Operation) error {
	switchBuilder := astbuilder.Switch(astbuilder.Sel(astbuilder.I("response"), "StatusCode"))

	for _, code := range codes {
		response := operation.Responses.Value(code)

		caseBodyBuilder := astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.IfNil(astbuilder.Sel(astbuilder.I("response"), "Response"+code)).WithBody(astbuilder.NewBodyBuilder().
				AddStmt(astbuilder.CallStmt(
					astbuilder.Sel(astbuilder.I("http"), "Error"),
					astbuilder.I("w"),
					astbuilder.Str("{\"error\":\"InternalServerError\"}"),
					astbuilder.Sel(astbuilder.I("http"), "StatusInternalServerError"),
				)).
				AddStmt(astbuilder.Return())))

		if len(response.Value.Headers) > 0 {
			caseBodyBuilder.AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.I("h"), "write"+baseName+code+"ResponseHeaders"),
				astbuilder.I("w"),
				astbuilder.Sel(astbuilder.I("response"), "Response"+code),
			))
		}

		if len(response.Value.Content) > 0 {
			if len(response.Value.Content) > 1 {
				return errors.New("multiple content types are not supported for response code " + code)
			}
			var contentType string
			for key := range response.Value.Content {
				contentType = key
				break
			}
			caseBodyBuilder.AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("w"), "Header")), "Set"),
				astbuilder.Str("Content-Type"),
				astbuilder.Str(g.getContentTypeHeadeValue(contentType)),
			))
		}

		caseBodyBuilder.
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("w"), "WriteHeader"), astbuilder.Sel(astbuilder.I("response"), "StatusCode"))).
			AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.I("h"), "write"+baseName+code+"Response"),
				astbuilder.I("w"),
				astbuilder.Sel(astbuilder.I("response"), "Response"+code),
			)).
			AddStmt(astbuilder.Return())

		switchBuilder.AddCase(astbuilder.Case(astbuilder.IntLit(code)).WithBody(caseBodyBuilder))
	}

	body := astbuilder.NewBodyBuilder().
		AddStatement(switchBuilder.Build()).
		AddStmt(astbuilder.CallStmt(
			astbuilder.Sel(astbuilder.I("http"), "Error"),
			astbuilder.I("w"),
			astbuilder.Str("{\"error\":\"InternalServerError\"}"),
			astbuilder.Sel(astbuilder.I("http"), "StatusInternalServerError"),
		))

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+"Response").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("response").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response").AsPointer(true))).
		WithBody(body).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, writeResponseFunc)
	return nil
}

func (g *Generator) getContentTypeHeadeValue(contentType string) string {
	textualContentType := map[string]struct{}{
		"text/plain":             {},
		"text/html":              {},
		"text/css":               {},
		"application/javascript": {},
		"application/xml":        {},
		"application/json":       {},
	}
	if _, ok := textualContentType[contentType]; ok {
		return fmt.Sprintf("%s; charset=utf-8", contentType)
	}
	return contentType
}

func (g *Generator) AddWriteHeadersForResponseCode(baseName string, code string, response *openapi3.ResponseRef) error {
	g.AddHandlersImport("encoding/json")

	httpErrorBody := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.CallStmt(
			astbuilder.Sel(astbuilder.I("http"), "Error"),
			astbuilder.I("w"),
			astbuilder.Str("{\"error\":\"InternalServerError\"}"),
			astbuilder.Sel(astbuilder.I("http"), "StatusInternalServerError"),
		)).
		AddStmt(astbuilder.Return())

	body := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DefineCallWithErr("headersJSON", astbuilder.Sel(astbuilder.I("json"), "Marshal"), astbuilder.Sel(astbuilder.I("r"), "Headers"))).
		AddStmt(astbuilder.IfErrNotNil().WithBody(httpErrorBody)).
		AddStmt(astbuilder.DeclareVarWithType("headers", astbuilder.MapOf(astbuilder.String(), astbuilder.String()))).
		AddStmt(astbuilder.Assign(astbuilder.I("err"), astbuilder.Call(astbuilder.Sel(astbuilder.I("json"), "Unmarshal"), astbuilder.I("headersJSON"), astbuilder.Amp(astbuilder.I("headers"))))).

		AddStmt(astbuilder.IfErrNotNil().WithBody(httpErrorBody)).
		AddStmt(astbuilder.Range("key", "value", astbuilder.I("headers")).WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(
				astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("w"), "Header")), "Set"),
				astbuilder.I("key"),
				astbuilder.I("value"),
			))))

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+code+"ResponseHeaders").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response"+code).AsPointer(true))).
		WithBody(body).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, writeResponseFunc)

	return nil
}

func (g *Generator) AddWriteResponseCode(baseName string, code string, response *openapi3.ResponseRef) error {
	bodyBuilder := astbuilder.NewBodyBuilder()

	if len(response.Value.Content) > 1 {
		return errors.New("multiple responses are not supported")
	}

	hasContent := false
	for key, value := range response.Value.Content {
		if key != applicationJSONCT {
			return errors.New("only application/json content type is supported")
		}
		if value.Schema != nil {
			hasContent = true
			g.AddHandlersImport("encoding/json")
			bodyBuilder.AddStmt(astbuilder.Assign(astbuilder.I("err"),
				astbuilder.Call(astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("json"), "NewEncoder"), astbuilder.I("w")), "Encode"),
					astbuilder.Sel(astbuilder.I("r"), "Body"),
				)))
			bodyBuilder.AddStmt(astbuilder.IfErrNotNil().WithBody(astbuilder.NewBodyBuilder().
				AddStmt(astbuilder.CallStmt(
					astbuilder.Sel(astbuilder.I("http"), "Error"),
					astbuilder.I("w"),
					astbuilder.Str("{\"error\":\"InternalServerError\"}"),
					astbuilder.Sel(astbuilder.I("http"), "StatusInternalServerError"),
				)).
				AddStmt(astbuilder.Return())))
		}
	}

	// Prepend var err error if we have content
	finalBody := astbuilder.NewBodyBuilder()
	if hasContent {
		finalBody.AddStmt(astbuilder.DeclareVar("err", astbuilder.I("error")))
	}
	for _, stmt := range bodyBuilder.Build().List {
		finalBody.AddStatement(stmt)
	}

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+code+"Response").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response"+code).AsPointer(true))).
		WithBody(finalBody).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, writeResponseFunc)

	return nil
}

func (g *Generator) AddParsePathParamsMethod(baseName string, params openapi3.Parameters) error {
	bodyBuilder := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DeclareVar("pathParams", astbuilder.Sel(astbuilder.I(g.GetCurrentModelsPackage()), baseName+"PathParams")))

	for _, param := range params {
		if param.Value.Schema == nil || param.Value.Schema.Value == nil {
			continue
		}

		varName := GoIdentLowercase(FormatGoLikeIdentifier(param.Value.Name))
		bodyBuilder.AddStmt(astbuilder.DefineCall(varName, astbuilder.Sel(astbuilder.I("chi"), "URLParam"), astbuilder.I("r"), astbuilder.Str(param.Value.Name)))
		bodyBuilder.AddStmt(astbuilder.If(astbuilder.Eq(astbuilder.I(varName), astbuilder.Str(""))).WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.Return2(astbuilder.I("nil"), astbuilder.Call(astbuilder.Sel(astbuilder.I("errors"), "New"), astbuilder.Str(param.Value.Name+" path param is required"))))))

		g.AddHandlersImport("github.com/go-faster/errors")
		switch {
		case param.Value.Schema.Value.Type.Permits("string"):
			bodyBuilder.AddStmt(astbuilder.Assign(
				astbuilder.Sel(astbuilder.I("pathParams"), FormatGoLikeIdentifier(param.Value.Name)),
				astbuilder.I(varName),
			))
		default:
			return errors.New(fmt.Sprintf("unsupported path parameter type: %v", param.Value.Schema.Value.Type)) //nolint:revive
		}
	}

	bodyBuilder.
		AddStmt(astbuilder.DefineCall("err", astbuilder.Sel(astbuilder.Sel(astbuilder.I("h"), "validator"), "Struct"), astbuilder.I("pathParams"))).
		AddStmt(astbuilder.IfErrNotNilReturn(astbuilder.I("nil"))).
		AddStmt(astbuilder.Return2(astbuilder.Amp(astbuilder.I("pathParams")), astbuilder.I("nil")))

	parsePathParamsFunc := astbuilder.NewFunctionBuilder().
		WithName("parse"+baseName+"PathParams").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true))).
		AddResult(astbuilder.NewFieldBuilder().WithType(astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"PathParams").AsPointer(true))).
		AddResult(astbuilder.ErrorField()).
		WithBody(bodyBuilder).
		Build()

	g.HandlersFile.restDecls = append(g.HandlersFile.restDecls, parsePathParamsFunc)

	return nil
}
