package generator

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-faster/errors"

	"github.com/sintoniastrategy/validgo-gen/internal/generator/astbuilder"
)

type HandlersFile struct {
	requiredFieldsArePointers bool
	packageName               string
	interfaceBuilders         []*astbuilder.InterfaceBuilder

	handlerDeclBuilder *astbuilder.StructBuilder

	handlerConstructorBuilder *astbuilder.FunctionBuilder
	handlerConstructorLit     *astbuilder.CompositeLitBuilder

	addRoutesBodyBuilder *astbuilder.BodyBuilder

	handleFuncBuilders   map[string]*astbuilder.FunctionBuilder
	handleSwitchBuilders map[string]*astbuilder.SwitchBuilder
	handleFuncOrder      []string
	handleFuncSlots      map[string]int // index of the nil placeholder in restBuilders

	restBuilders          []*astbuilder.FunctionBuilder
	hasContainsNullMethod bool
}

func (g *Generator) InitHandlerImports() {
	g.AddHandlersImport("github.com/go-playground/validator/v10")
	g.AddHandlersImport("github.com/go-chi/chi/v5")
}

func (g *Generator) InitHandlerStruct() {
	g.HandlersFile.handlerDeclBuilder = astbuilder.NewStructBuilder().WithName("Handler").
		AddField(astbuilder.NewFieldBuilder().WithName("validator").WithType(
			astbuilder.NewSimpleTypeBuilder().AddElements("validator", "Validate").AsPointer(true)))
}

func (g *Generator) InitHandlerConstructor() {
	g.HandlersFile.handlerConstructorLit = astbuilder.NewCompositeLitBuilder(astbuilder.Ident("Handler")).
		AddKeyValue("validator", astbuilder.Call(astbuilder.Sel(astbuilder.I("validator"), "New"), astbuilder.Call(astbuilder.Sel(astbuilder.I("validator"), "WithRequiredStructEnabled"))).Build())
	g.HandlersFile.handlerConstructorBuilder = astbuilder.NewFunctionBuilder().
		WithName("NewHandler").
		AddResult(astbuilder.NewFieldBuilder().WithType(astbuilder.Ident("Handler").AsPointer(true)))
}

func (g *Generator) InitRoutesFunc() {
	g.HandlersFile.addRoutesBodyBuilder = astbuilder.NewBodyBuilder()
}

func (g *Generator) InitHandlerFields(packageName string) {
	g.HandlersFile.packageName = packageName

	g.InitHandlerImports()

	g.InitHandlerStruct()

	g.InitHandlerConstructor()

	g.InitRoutesFunc()
}

func (g *Generator) NewHandlersFile() {
	g.HandlersFile = &HandlersFile{
		requiredFieldsArePointers: g.Opts.RequiredFieldsArePointers,
	}
}

func (g *Generator) WriteHandlersToOutput(output io.Writer) error {
	const op = "generator.HandlersFile.WriteToOutput"
	// go/ast package is great!
	_, err := output.Write([]byte("// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.\n\n"))
	if err != nil {
		return errors.Wrap(err, op)
	}

	file := g.GenerateHandlersFile()
	err = format.Node(output, token.NewFileSet(), file)
	if err != nil {
		return errors.Wrap(err, op)
	}

	return nil
}

func (g *Generator) AddHandlersInterface(name string, methodName string, requestName string, responseName string) {
	interfaceBuilder := astbuilder.NewInterfaceBuilder().WithName(name).WithMethod(
		astbuilder.NewInterfaceMethodBuilder().WithName(methodName).
			AddArgField(
				astbuilder.NewFieldBuilder().WithName("ctx").WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements("context", "Context"),
				)).
			AddArgField(
				astbuilder.NewFieldBuilder().WithName("r").WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements(
						g.GetCurrentModelsPackage(), requestName,
					))).
			AddRetvalField(
				astbuilder.NewFieldBuilder().WithType(
					astbuilder.NewSimpleTypeBuilder().AddElements(
						g.GetCurrentModelsPackage(), responseName,
					).AsPointer(true))).
			AddRetvalField(
				astbuilder.NewFieldBuilder().WithType(
					astbuilder.NewSimpleTypeBuilder().AddElement("error")),
			),
	)

	g.HandlersFile.interfaceBuilders = append(g.HandlersFile.interfaceBuilders, interfaceBuilder)
}

func (g *Generator) AddDependencyToHandlers(baseName string) {
	fieldName := GoIdentLowercase(baseName)

	g.HandlersFile.handlerDeclBuilder.AddField(
		astbuilder.NewFieldBuilder().WithName(fieldName).WithType(
			astbuilder.NewSimpleTypeBuilder().AddElement(baseName + "Handler")))

	g.HandlersFile.handlerConstructorBuilder.AddParam(astbuilder.IdentField(fieldName, baseName+"Handler"))

	g.HandlersFile.handlerConstructorLit.AddKeyValue(fieldName, astbuilder.I(fieldName).Build())
}

func (g *Generator) AddHandlersImport(path string) {
	g.HandlerImportsBuilder.AddImport(path)
}

func (g *Generator) GenerateHandlersFile() *ast.File {
	importSpecs, declSpecs := g.HandlerImportsBuilder.Build()

	g.FinalizeHandlerSwitches()

	constructorBody := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.Return1(astbuilder.Amp(g.HandlersFile.handlerConstructorLit).Build()))
	constructorDecl := g.HandlersFile.handlerConstructorBuilder.
		WithBody(constructorBody).
		Build()

	addRoutesDecl := astbuilder.NewFunctionBuilder().
		WithName("AddRoutes").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("router").WithType(astbuilder.Selector("chi", "Router"))).
		WithBody(g.HandlersFile.addRoutesBodyBuilder).
		Build()

	fb := astbuilder.NewFileBuilder(g.HandlersFile.packageName).
		WithImports(importSpecs, declSpecs)
	for _, b := range g.HandlersFile.interfaceBuilders {
		fb.AddDecl(b.Build())
	}
	fb.AddDecl(g.HandlersFile.handlerDeclBuilder.BuildAsDeclaration())
	fb.AddDecl(constructorDecl)
	fb.AddDecl(addRoutesDecl)
	for _, b := range g.HandlersFile.restBuilders {
		if b != nil {
			fb.AddDecl(b.Build())
		}
	}

	return fb.Build()
}

func (g *Generator) AddRouteToRouter(baseName string, method string, pathName string) {
	g.HandlersFile.addRoutesBodyBuilder.AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("router"),   method), astbuilder.Str(pathName), astbuilder.Sel(astbuilder.I("h"),   "handle"+baseName)))
}

func (g *Generator) GetHandler(baseName string) *astbuilder.SwitchBuilder {
	if g.HandlersFile.handleSwitchBuilders == nil {
		return nil
	}
	return g.HandlersFile.handleSwitchBuilders[baseName]
}

func (g *Generator) CreateHandler(baseName string) {
	g.AddHandlersImport("mime")

	if g.HandlersFile.handleFuncBuilders == nil {
		g.HandlersFile.handleFuncBuilders = make(map[string]*astbuilder.FunctionBuilder)
		g.HandlersFile.handleSwitchBuilders = make(map[string]*astbuilder.SwitchBuilder)
		g.HandlersFile.handleFuncSlots = make(map[string]int)
	}

	funcBuilder := astbuilder.NewFunctionBuilder().
		WithName("handle"+baseName).
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true)))

	g.HandlersFile.handleFuncBuilders[baseName] = funcBuilder
	g.HandlersFile.handleSwitchBuilders[baseName] = astbuilder.Switch(astbuilder.I("contentType").Build())
	g.HandlersFile.handleFuncOrder = append(g.HandlersFile.handleFuncOrder, baseName)
	// Reserve a slot in restDecls at the current position
	g.HandlersFile.handleFuncSlots[baseName] = len(g.HandlersFile.restBuilders)
	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, nil)
}

// CreateDirectHandler generates a handler that directly delegates to the request handler
// without checking Content-Type. Used for operations with no request body (e.g. GET, DELETE)
// where Content-Type is irrelevant.
func (g *Generator) CreateDirectHandler(baseName string) {
	handleFunc := astbuilder.NewFunctionBuilder().
		WithName("handle" + baseName).
		WithReceiver(astbuilder.NewFieldBuilder().
			WithName("h").
			WithType(astbuilder.Ident("Handler").AsPointer(true))).
		AddParams(
			astbuilder.SelectorField("w", "http", "ResponseWriter"),
			astbuilder.NewFieldBuilder().
				WithName("r").
				WithType(astbuilder.Selector("http", "Request").AsPointer(true)),
		).
		WithBody(astbuilder.NewBodyBuilder().
			Call(astbuilder.Sel(astbuilder.I("h"), "handle"+baseName+"Request"), astbuilder.I("w"), astbuilder.I("r")),
		)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, handleFunc)
}

func (g *Generator) FinalizeHandlerSwitches() {
	if g.HandlersFile.handleSwitchBuilders == nil {
		return
	}
	for _, baseName := range g.HandlersFile.handleFuncOrder {
		switchBuilder := g.HandlersFile.handleSwitchBuilders[baseName]
		switchBuilder.AddCase(astbuilder.Default().WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"Unsupported Content-Type\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusUnsupportedMediaType"))).
			AddStmt(astbuilder.Return()),
		))
		bodyBuilder := astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.NewDefineBuilder().
				Lhs(astbuilder.I("contentType").Build(), astbuilder.I("_").Build(), astbuilder.I("_").Build()).
				AddRhs(astbuilder.Call(astbuilder.Sel(astbuilder.I("mime"), "ParseMediaType"), astbuilder.Call(astbuilder.Sel(astbuilder.I("r.Header"), "Get"), astbuilder.Str("Content-Type"))).Build())).
			AddStmt(switchBuilder)
		g.HandlersFile.handleFuncBuilders[baseName].WithBody(bodyBuilder)
		// Fill the reserved slot in restBuilders
		g.HandlersFile.restBuilders[g.HandlersFile.handleFuncSlots[baseName]] = g.HandlersFile.handleFuncBuilders[baseName]
	}
}

func (g *Generator) AddContentTypeHandler(baseName string, rawContentType string) {
	if g.HandlersFile.handleSwitchBuilders == nil {
		return
	}
	switchBuilder, ok := g.HandlersFile.handleSwitchBuilders[baseName]
	if !ok {
		return
	}
	caseBody := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"),   "handle"+baseName+"Request"), astbuilder.I("w"), astbuilder.I("r"))).
		AddStmt(astbuilder.Return())

	switchBuilder.AddCase(astbuilder.Case(astbuilder.Str(rawContentType).Build()).WithBody(caseBody))

	if rawContentType == applicationJSONCT {
		switchBuilder.AddCase(astbuilder.Case(astbuilder.Str("").Build()).WithBody(caseBody))
	}
}

func (g *Generator) AddHandleOperationMethodHandlers(baseName string) {
	body := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DefineCallWithErr("request", astbuilder.Sel(astbuilder.I("h"),   "parse"+baseName+"Request"), astbuilder.I("r"))).
		AddStmt(astbuilder.IfErrNotNil().WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Call(astbuilder.Sel(astbuilder.I("fmt"),   "Sprintf"), astbuilder.Str("{\"error\":%s}"), astbuilder.Call(astbuilder.Sel(astbuilder.I("strconv"),   "Quote"), astbuilder.Call(astbuilder.Sel(astbuilder.I("err"),   "Error")))), astbuilder.Sel(astbuilder.I("http"),   "StatusBadRequest"))).
			AddStmt(astbuilder.Return()))).
		AddStmt(astbuilder.DefineCall("ctx", astbuilder.Sel(astbuilder.I("r"),   "Context"))).
		AddStmt(astbuilder.DefineCallWithErr("response", astbuilder.Sel(astbuilder.Sel(astbuilder.I("h"),   GoIdentLowercase(baseName)),   "Handle"+baseName), astbuilder.I("ctx"), astbuilder.Star(astbuilder.Ident("request")))).
		AddStmt(astbuilder.If(astbuilder.Or(astbuilder.Ne(astbuilder.I("err"), astbuilder.I("nil")), astbuilder.Eq(astbuilder.I("response"), astbuilder.I("nil"))).Build()).
			WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"InternalServerError\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusInternalServerError"))).
			AddStmt(astbuilder.Return()))).
		AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"),   "write"+baseName+"Response"), astbuilder.I("w"), astbuilder.I("response"))).
		AddStmt(astbuilder.Return())

	fn := astbuilder.NewFunctionBuilder().
		WithName("handle"+baseName+"Request").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true))).
		WithBody(body)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, fn)
	g.AddHandlersImport("fmt")
	g.AddHandlersImport("strconv")
}

func (g *Generator) AddWriteResponseMethodHandlers(baseName string, codes []string, operation *openapi3.Operation) error {
	switchBuilder := astbuilder.Switch(astbuilder.Sel(astbuilder.I("response"),   "StatusCode").Build())

	for _, code := range codes {
		response := operation.Responses.Value(code)

		caseBodyBuilder := astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.IfNil(astbuilder.Sel(astbuilder.I("response"),  "Response"+code).Build()).WithBody(astbuilder.NewBodyBuilder().
				AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"InternalServerError\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusInternalServerError"))).
				AddStmt(astbuilder.Return())))

		if len(response.Value.Headers) > 0 {
			caseBodyBuilder.AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"),   "write"+baseName+code+"ResponseHeaders"), astbuilder.I("w"), astbuilder.Sel(astbuilder.I("response"),   "Response"+code)))
		}

		if len(response.Value.Content) > 0 {
			if len(response.Value.Content) > 1 {
				return errors.New("multiple content types are not supported for response code " + code)
			}
			var contentType string
			for key := range response.Value.Content {
				contentType = key
				break
			}
			caseBodyBuilder.AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("w"),   "Header")),   "Set"), astbuilder.Str("Content-Type"), astbuilder.Str(g.getContentTypeHeadeValue(contentType))))
		}

		caseBodyBuilder.
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("w"),   "WriteHeader"), astbuilder.Sel(astbuilder.I("response"),   "StatusCode"))).
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("h"),   "write"+baseName+code+"Response"), astbuilder.I("w"), astbuilder.Sel(astbuilder.I("response"),   "Response"+code))).
			AddStmt(astbuilder.Return())

		switchBuilder.AddCase(astbuilder.Case(astbuilder.IntLit(code).Build()).WithBody(caseBodyBuilder))
	}

	body := astbuilder.NewBodyBuilder().
		AddStatement(switchBuilder.Build()).
		AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"InternalServerError\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusInternalServerError")))

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+"Response").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("response").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response").AsPointer(true))).
		WithBody(body)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, writeResponseFunc)
	return nil
}

func (g *Generator) getContentTypeHeadeValue(contentType string) string {
	textualContentType := map[string]struct{}{
		"text/plain":             {},
		"text/html":              {},
		"text/css":               {},
		"application/javascript": {},
		"application/xml":        {},
		"application/json":       {},
	}
	if _, ok := textualContentType[contentType]; ok {
		return fmt.Sprintf("%s; charset=utf-8", contentType)
	}
	return contentType
}

func (g *Generator) AddWriteHeadersForResponseCode(baseName string, code string, response *openapi3.ResponseRef) error {
	g.AddHandlersImport("encoding/json")

	httpErrorBody := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"InternalServerError\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusInternalServerError"))).
		AddStmt(astbuilder.Return())

	body := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DefineCallWithErr("headersJSON", astbuilder.Sel(astbuilder.I("json"),   "Marshal"), astbuilder.Sel(astbuilder.I("r"),   "Headers"))).
		AddStmt(astbuilder.IfErrNotNil().WithBody(httpErrorBody)).
		AddStmt(astbuilder.DeclareVarWithType("headers", astbuilder.MapOf(astbuilder.String(), astbuilder.String()))).
		AddStmt(astbuilder.Assign(astbuilder.I("err").Build(),  astbuilder.Call(astbuilder.Sel(astbuilder.I("json"),  "Unmarshal"), astbuilder.I("headersJSON"), astbuilder.Amp(astbuilder.Ident("headers"))).Build())).

		AddStmt(astbuilder.IfErrNotNil().WithBody(httpErrorBody)).
		AddStmt(astbuilder.Range("key", "value", astbuilder.I("headers").Build()).WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("w"),   "Header")),   "Set"), astbuilder.I("key"), astbuilder.I("value")))))

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+code+"ResponseHeaders").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response"+code).AsPointer(true))).
		WithBody(body)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, writeResponseFunc)

	return nil
}

func (g *Generator) AddWriteResponseCode(baseName string, code string, response *openapi3.ResponseRef) error {
	if len(response.Value.Content) > 1 {
		return errors.New("multiple responses are not supported")
	}

	hasContent := false
	for key, value := range response.Value.Content {
		if key != applicationJSONCT {
			return errors.New("only application/json content type is supported")
		}
		if value.Schema != nil {
			hasContent = true
		}
	}

	bodyBuilder := astbuilder.NewBodyBuilder()
	if hasContent {
		g.AddHandlersImport("encoding/json")
		bodyBuilder.AddStmt(astbuilder.DeclareVar("err", astbuilder.I("error").Build()))
		for _, value := range response.Value.Content {
			if value.Schema != nil {
				bodyBuilder.AddStmt(astbuilder.Assign(astbuilder.I("err").Build(), 
					astbuilder.Call(astbuilder.Sel(astbuilder.Call(astbuilder.Sel(astbuilder.I("json"),  "NewEncoder"), astbuilder.I("w")),  "Encode"), astbuilder.Sel(astbuilder.I("r"),  "Body")).Build()))
				bodyBuilder.AddStmt(astbuilder.IfErrNotNil().WithBody(astbuilder.NewBodyBuilder().
					AddStmt(astbuilder.CallStmt(astbuilder.Sel(astbuilder.I("http"),   "Error"), astbuilder.I("w"), astbuilder.Str("{\"error\":\"InternalServerError\"}"), astbuilder.Sel(astbuilder.I("http"),   "StatusInternalServerError"))).
					AddStmt(astbuilder.Return())))
			}
		}
	}

	writeResponseFunc := astbuilder.NewFunctionBuilder().
		WithName("write"+baseName+code+"Response").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("w").WithType(astbuilder.Selector("http", "ResponseWriter"))).
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(
			astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"Response"+code).AsPointer(true))).
		WithBody(bodyBuilder)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, writeResponseFunc)

	return nil
}

func (g *Generator) AddParsePathParamsMethod(baseName string, params openapi3.Parameters) error {
	bodyBuilder := astbuilder.NewBodyBuilder().
		AddStmt(astbuilder.DeclareVar("pathParams", astbuilder.Sel(astbuilder.I(g.GetCurrentModelsPackage()),   baseName+"PathParams").Build()))

	for _, param := range params {
		if param.Value.Schema == nil || param.Value.Schema.Value == nil {
			continue
		}

		varName := GoIdentLowercase(FormatGoLikeIdentifier(param.Value.Name))
		bodyBuilder.AddStmt(astbuilder.DefineCall(varName, astbuilder.Sel(astbuilder.I("chi"),   "URLParam"), astbuilder.I("r"), astbuilder.Str(param.Value.Name)))
		bodyBuilder.AddStmt(astbuilder.If(astbuilder.Eq(astbuilder.I(varName), astbuilder.Str("")).Build()).WithBody(astbuilder.NewBodyBuilder().
			AddStmt(astbuilder.Return2(astbuilder.I("nil").Build(),  astbuilder.Call(astbuilder.Sel(astbuilder.I("errors"),  "New"), astbuilder.Str(param.Value.Name+" path param is required")).Build()))))

		g.AddHandlersImport("github.com/go-faster/errors")
		switch {
		case param.Value.Schema.Value.Type.Permits("string"):
			bodyBuilder.AddStmt(astbuilder.Assign(
				astbuilder.Sel(astbuilder.I("pathParams"),  FormatGoLikeIdentifier(param.Value.Name)).Build(), 
				astbuilder.I(varName).Build()))
		default:
			return errors.New(fmt.Sprintf("unsupported path parameter type: %v", param.Value.Schema.Value.Type)) //nolint:revive
		}
	}

	bodyBuilder.
		AddStmt(astbuilder.DefineCall("err", astbuilder.Sel(astbuilder.Sel(astbuilder.I("h"),   "validator"),   "Struct"), astbuilder.I("pathParams"))).
		AddStmt(astbuilder.IfErrNotNilReturn(astbuilder.I("nil").Build())).
		AddStmt(astbuilder.Return2(astbuilder.Amp(astbuilder.Ident("pathParams")).Build(),  astbuilder.I("nil").Build()))

	parsePathParamsFunc := astbuilder.NewFunctionBuilder().
		WithName("parse"+baseName+"PathParams").
		WithPointerReceiver("h", "Handler").
		AddParam(astbuilder.NewFieldBuilder().WithName("r").WithType(astbuilder.Selector("http", "Request").AsPointer(true))).
		AddResult(astbuilder.NewFieldBuilder().WithType(astbuilder.Selector(g.GetCurrentModelsPackage(), baseName+"PathParams").AsPointer(true))).
		AddResult(astbuilder.ErrorField()).
		WithBody(bodyBuilder)

	g.HandlersFile.restBuilders = append(g.HandlersFile.restBuilders, parsePathParamsFunc)

	return nil
}
